heroes_list = [
    "Bangalore",
    "Revenant",
    "Fuse",
    "Ash",
    "Mad Maggie",
    "Pathfinder",
    "Wraith",
    "Mirage",
    "Octane",
    "Horizon",
    "Valkyrie",
    "Bloodhound",
    "Crypto",
    "Seer",
    "Vantage",
    "Gibraltar",
    "Lifeline",
    "Loba",
    "Newcastle",
    "Caustic",
    "Wattson",
    "Rampart",
    "Catalyst",
]

weapons_list = [
    "HAVOC Rifle",
    "VK-47 Flatline",
    "Hemlok Burst AR",
    "Nemesis Burst AR",
    "R-301 Carbine",
    "Alternator SMG",
    "Prowler Burst PDW",
    "R-99 SMG",
    "Volt SMG",
    "C.A.R. SMG",
    "Devotion LMG",
    "L-STAR EMG",
    "M600 Spitfire",
    "Rampage LMG",
    "G7 Scout",
    "Triple Take",
    "30-30 Repeater",
    "Bocek Compound Bow",
    "Charge Rifle",
    "Longbow DMR",
    "Kraber .50-Cal Sniper",
    "Sentinel",
    "EVA-8 Auto",
    "Mastiff Shotgun",
    "Mozambique Shotgun",
    "Peacekeeper",
    "RE-45 Auto",
    "P2020",
    "Wingman",
]

map_list = [
    "Kings Canyon",
    "World's Edge",
    "Olympus",
    "Storm Point",
    "Broken Moon",
    "Party Crasher",
    "Phase Runner",
    "Overflow",
    "Encore",
    "Habitat 4",
    "Drop-Off",
]
